name: "ImageOnMap"
main: "dev.tehbrian.imageonmap.ImageOnMap"
version: "${project.version}"
api-version: "1.20"

commands:
  tomap:
    description: Render an image onto a map.
    usage: /<command> [url]
  maptool:
    description: Manage your maps.
    usage: /<command>
  maps:
    description: See your maps.
    usage: /<command>
  givemap:
    description: Give to a player a map from another player's map store.
    usage: /<command> [player_from] player_to map_name

permissions:
  imageonmap.*:
    description: "Grants all non-administrative permissions."
    default: true
    children:
      imageonmap.userender: true
      imageonmap.new: true
      imageonmap.list: true
      imageonmap.listother: false
      imageonmap.get: true
      imageonmap.getother: false
      imageonmap.explore: true
      imageonmap.exploreother: false
      imageonmap.rename: true
      imageonmap.placesplattermap: true
      imageonmap.removesplattermap: true
      imageonmap.delete: true
      imageonmap.deleteother: false
      imageonmap.bypasssize: false
      imageonmap.give: false
      imageonmap.update: true
      imageonmap.updateother: false

  imageonmap.new:
    description: "Permission to use /tomap and related commands."
    default: true

  imageonmap.rename:
    description: "Permission to rename a map."
    default: true

  imageonmap.list:
    description: "Permission to list your rendered maps."
    default: true

  imageonmap.listother:
    description: "Permission to list another player's rendered maps."
    default: op

  imageonmap.get:
    description: "Permission to retrieve a map from your rendered maps."
    default: true

  imageonmap.getother:
    description: "Permission to retrieve a map from another player's rendered maps."
    default: op

  imageonmap.explore:
    description: "Permission to list your maps in a GUI."
    default: true

  imageonmap.exploreother:
    description: "Permission to list another player's maps in a GUI."
    default: op

  imageonmap.delete:
    description: "Permission to delete a map."
    default: true

  imageonmap.deleteother:
    description: "Permission to delete another player's map."
    default: op

  imageonmap.update:
    description: "Permission to render a new image onto your old map."
    default: true

  imageonmap.updateother:
    description: "Permission to render a new image onto another player's old map."
    default: op

  imageonmap.give:
    description: "Permission to give a map to a specified player."
    default: op

  imageonmap.placesplattermap:
    description: "Permission to place a splatter map."
    default: true

  imageonmap.removesplattermap:
    description: "Permission to remove a splatter map when sneaking."
    default: true

  imageonmap.administrative:
    description: "Permission to perform administrative tasks, such as /maptool migrate."
    default: op

  imageonmap.bypasssize:
    description: "Permission to create maps larger than the configured limit."
    default: op
