name: Release on tag

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Set up JDK 21
        uses: actions/setup-java@v5.0.0
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven
          # these three enable publishing to GitHub Packages without editing settings.xml manually
          server-id: github
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}

      - name: Derive version from tag
        id: vars
        run: |
          VERSION="${GITHUB_REF_NAME#v}"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Set Maven project version (remove -SNAPSHOT)
        run: mvn -B versions:set -DnewVersion=${{ steps.vars.outputs.version }} -DgenerateBackupPoms=false

      - name: Build with Maven
        run: mvn -B -DskipTests package

      - name: Publish to GitHub Packages (Maven)
        run: |
          mvn -B -DskipTests \
            -DaltDeploymentRepository=github::https://maven.pkg.github.com/${{ github.repository }} \
            deploy

      - name: Create GitHub Release and upload JAR
        uses: softprops/action-gh-release@v2.3.2
        with:
          tag_name: ${{ github.ref_name }}
          name: ImageOnMap v${{ steps.vars.outputs.version }}
          files: |
            target/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}